name: AutoMLOps CI Workflow

on:
  push:
    branches:
      - main
      - 'github-integration'
  pull_request:
    branches:
      - main
  merge_group:
    branches:
      - main

jobs:
  test:
    # Official language image. Look for the different tagged releases at:
    # https://hub.docker.com/r/library/python/tags/
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Check for licenses
      run: |
        ./license_check.sh
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/1063498356496/locations/global/workloadIdentityPools/integration-testing-pool/providers/github'
        service_account: '1063498356496-compute@developer.iam.gserviceaccount.com'
        

    # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    # Now you can run gcloud commands authenticated as the impersonated service account.
    - id: 'gcloud'
      name: 'test auth by listing storage'
      run: |-
        gcloud storage buckets list

    - run: echo "🍏 This job's status is ${{ job.status }}."
    - name: Run integration tests
      working-directory: tests/integration
      run: |
        pytest 
